export const members = [
  {
    "S.N.": 1,
    Name: "Ameera Maharjan",
    "Membership ID": "BIM AM 051",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9818452865,
  },
  {
    "S.N.": 2,
    Name: "Anish Maharjan",
    "Membership ID": "BIM AM 052",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9840151586,
  },
  {
    "S.N.": 3,
    Name: "Anish Shrestha",
    "Membership ID": "BIM AS 053",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9843125788,
  },
  {
    "S.N.": 4,
    Name: "Anjal Shrestha",
    "Membership ID": "BIM AS 054",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9840044662,
  },
  {
    "S.N.": 5,
    Name: "Ayush Joshi",
    "Membership ID": "BIM AJ 055",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9840748401,
  },
  {
    "S.N.": 6,
    Name: "Bibhusha Bajracharya",
    "Membership ID": "BIM BB 056",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9840255659,
  },
  {
    "S.N.": 7,
    Name: "Ganesh Tamang",
    "Membership ID": "BIM GT 057",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9813000270,
  },
  {
    "S.N.": 8,
    Name: "Ishan Shrestha",
    "Membership ID": "BIM IS 058",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9803329374,
  },
  {
    "S.N.": 9,
    Name: "Kusum Maharjan",
    "Membership ID": "BIM KM 059",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": "9808523448 9863468648",
  },
  {
    "S.N.": 10,
    Name: "Likesh Maharjan",
    "Membership ID": "BIM LM 060",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9848870768,
  },
  {
    "S.N.": 11,
    Name: "Lumanti Devi Maharjan",
    "Membership ID": "BIM LDM 061",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9862403879,
  },
  {
    "S.N.": 12,
    Name: "Manindra Prasad Joshi",
    "Membership ID": "BIM MPJ 062",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9861490503,
  },
  {
    "S.N.": 13,
    Name: "Manish Maharjan",
    "Membership ID": "BIM MM 063",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9862450550,
  },
  {
    "S.N.": 14,
    Name: "Nischal Shrestha",
    "Membership ID": "BIM NS 064",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9860397374,
  },
  {
    "S.N.": 15,
    Name: "Pranita Rai",
    "Membership ID": "BIM PR 065 E",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9861148599,
  },
  {
    "S.N.": 16,
    Name: "Prashant Ghalan Tamang",
    "Membership ID": "BIM PGT 066",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9863485408,
  },
  {
    "S.N.": 17,
    Name: "Ranjana Bista",
    "Membership ID": "BIM RB 067",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9865495293,
  },
  {
    "S.N.": 18,
    Name: "Rekish Maharjan",
    "Membership ID": "BIM RM 068",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9860858239,
  },
  {
    "S.N.": 19,
    Name: "Riya Bajracharya",
    "Membership ID": "BIM RB 069",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9813137489,
  },
  {
    "S.N.": 20,
    Name: "Rupesh Basnet",
    "Membership ID": "BIM RB 070",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9869726899,
  },
  {
    "S.N.": 21,
    Name: "Sabina Tamang",
    "Membership ID": "BIM ST 071",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9864335836,
  },
  {
    "S.N.": 22,
    Name: "Samit Pudasaini",
    "Membership ID": "BIM SP 072",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9840734128,
  },
  {
    "S.N.": 23,
    Name: "Shishir Maharjan",
    "Membership ID": "BIM SM 073",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9869224533,
  },
  {
    "S.N.": 24,
    Name: "Simran Basnet",
    "Membership ID": "BIM SB 074",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9860357022,
  },
  {
    "S.N.": 25,
    Name: "Suman Chaudhary",
    "Membership ID": "BIM SC 075",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9860903489,
  },
  {
    "S.N.": 26,
    Name: "Ujjwal Maharjan",
    "Membership ID": "BIM UM 076",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9840209417,
  },
  {
    "S.N.": 27,
    Name: "Rajana Thapa",
    "Membership ID": "BIM RT 077",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9813996932,
  },
  {
    "S.N.": 28,
    Name: "Aastha Tuladhar ",
    "Membership ID": "BIM AT 078",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9808010594,
  },
  {
    "S.N.": 29,
    Name: "Jason Basumatary",
    "Membership ID": "BIM JB 079",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9817914136,
  },
  {
    "S.N.": 30,
    Name: "Jatin Bhatt",
    "Membership ID": "BIM JB 080",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9810771047,
  },
  {
    "S.N.": 31,
    Name: "Kaushal Rupakheti",
    "Membership ID": "BIM KR 081",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9842086499,
  },
  {
    "S.N.": 32,
    Name: "Nikhil Dangol",
    "Membership ID": "BIM ND 082",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9840121771,
  },
  {
    "S.N.": 33,
    Name: "Pawan Ghimire",
    "Membership ID": "BIM PG 083",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9861242880,
  },
  {
    "S.N.": 34,
    Name: "Prabhat Darsandhari",
    "Membership ID": "BIM PD 084",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9868822238,
  },
  {
    "S.N.": 35,
    Name: "Praful Bajracharya",
    "Membership ID": "BIM PB 085",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9880078380,
  },
  {
    "S.N.": 36,
    Name: "Pramesh Kumar Kunwar",
    "Membership ID": "BIM PKK 086",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9840122944,
  },
  {
    "S.N.": 37,
    Name: "Pratik Yonjon",
    "Membership ID": "BIM PY 087",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9808954002,
  },
  {
    "S.N.": 38,
    Name: "Pratima Pandey",
    "Membership ID": "BIM PP 088",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9818275181,
  },
  {
    "S.N.": 39,
    Name: "Priyanka Pandey",
    "Membership ID": "BIM PP 089",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9823532287,
  },
  {
    "S.N.": 40,
    Name: "Safeen Bajracharya",
    "Membership ID": "BIM SB 090",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": "9823181334 9810333699",
  },
  {
    "S.N.": 41,
    Name: "Saraswati Aryal",
    "Membership ID": "BIM SA 091",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9847711601,
  },
  {
    "S.N.": 42,
    Name: "Shovana Darji",
    "Membership ID": "BIM SD 092",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9840920236,
  },
  {
    "S.N.": 43,
    Name: "Sonam Tsewang Thapa",
    "Membership ID": "BIM STT 093",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9864332500,
  },
  {
    "S.N.": 44,
    Name: "Sujit Moktan",
    "Membership ID": "BIM SM 094",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9818861448,
  },
  {
    "S.N.": 45,
    Name: "Yubraj Ale",
    "Membership ID": "BIM YA 095",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9817729882,
  },
  {
    "S.N.": 46,
    Name: "Lujal Maharjan",
    "Membership ID": "BIM LM 131",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": "9803369759 9869647340",
  },
  {
    "S.N.": 47,
    Name: "Prasamsa Maskey",
    "Membership ID": "BIM PM 132",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9840341137,
  },
  {
    "S.N.": 48,
    Name: "Niva Maharjan",
    "Membership ID": "BIM NM 133",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9860569462,
  },
  {
    "S.N.": 49,
    Name: "Looniva Shakya",
    "Membership ID": "BIM LS 134",
    Faculty: "BIM",
    Semester: "5th 'A'",
    "Phone Number": 9840711797,
  },
  {
    "S.N.": 50,
    Name: "Manju Shree Singh",
    "Membership ID": "BIM MSS 143",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9840033123,
  },
  {
    "S.N.": 51,
    Name: "Manita Chitrakar",
    "Membership ID": "BIM MC 144",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9842551800,
  },
  {
    "S.N.": 52,
    Name: "Suman Kumar Karna",
    "Membership ID": "BIM SKK 145",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9862569816,
  },
  {
    "S.N.": 53,
    Name: "Kabin Maharjan",
    "Membership ID": "BIM KM 147",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9861520827,
  },
  {
    "S.N.": 54,
    Name: "Aashish Shahi",
    "Membership ID": "BIM AS 148",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9860557538,
  },
  {
    "S.N.": 55,
    Name: "Karun Thapa",
    "Membership ID": "BIM KT 149",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9807387808,
  },
  {
    "S.N.": 56,
    Name: "Rashmi Bhattarai",
    "Membership ID": "BIM RB 150",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9862230366,
  },
  {
    "S.N.": 57,
    Name: "Rubi Giri",
    "Membership ID": "BIM RG 037",
    Faculty: "BIM",
    Semester: "5th 'B'",
    "Phone Number": 9823553711,
  },
  {
    "S.N.": 58,
    Name: "Ajay Lama",
    Semester: "5th 'A'",
    "Phone Number": 9818452865,
  },
  {
    "S.N.": 59,
    Name: "Sandip Shrestha",
    Semester: "5th 'A'",
    "Phone Number": 9804393618,
  },
  {
    "S.N.": "BIM THIRD SEMESTER MEMBERSHIP LIST",
  },
  {
    "S.N.": 1,
    Name: "Aayusha Neupane",
    "Membership ID": "BIM AN 135",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9748260913,
  },
  {
    "S.N.": 2,
    Name: "Amitav Bajracharya",
    "Membership ID": "BIM AB 136",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9843504265,
  },
  {
    "S.N.": 3,
    Name: "Arpit Thapa Magar",
    "Membership ID": "BIM ATM 137",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9828942096,
  },
  {
    "S.N.": 4,
    Name: "Prilaz Shrestha",
    "Membership ID": "BIM PS 138",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9808371730,
  },
  {
    "S.N.": 5,
    Name: "Shraddha Shakya",
    "Membership ID": "BIM SS 139",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9808017251,
  },
  {
    "S.N.": 6,
    Name: "Sunita Pandey",
    "Membership ID": "BIM SP 140",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9862485077,
  },
  {
    "S.N.": 7,
    Name: "Sushil Thapa",
    "Membership ID": "BIM ST 141",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9814160683,
  },
  {
    "S.N.": 8,
    Name: "Yachu Shrestha",
    "Membership ID": "BIM YS 142",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9818521125,
  },
  {
    "S.N.": 9,
    Name: "Lashata Shakya",
    "Membership ID": "BIM LS 405",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9818824174,
  },
  {
    "S.N.": 10,
    Name: "Diganta Shakya",
    "Membership ID": "BIM DS 406",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9813567487,
  },
  {
    "S.N.": 11,
    Name: "Rohan Yongal Shrestha",
    "Membership ID": "BIM RS 121 E",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9863032844,
  },
  {
    "S.N.": 12,
    Name: "Smarika Shakya",
    "Membership ID": "BIM SS 404",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9843800335,
  },
  {
    "S.N.": 13,
    Name: "Aashish Maharjan",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9843844921,
  },
  {
    "S.N.": 14,
    Name: "Abhiraj Singh",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9817885405,
  },
  {
    "S.N.": 15,
    Name: "Anjila Shah",
    "Membership ID": "BIM AS 431",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9863770521,
  },
  {
    "S.N.": 16,
    Name: "Balananda Wagle",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9863354325,
  },
  {
    "S.N.": 17,
    Name: "Binaya Shrestha",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9818847755,
  },
  {
    "S.N.": 18,
    Name: "Hemanta Karki",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9844347294,
  },
  {
    "S.N.": 19,
    Name: "Ikswam Hang Rai",
    "Membership ID": "BIM IHR 434",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9863483232,
  },
  {
    "S.N.": 20,
    Name: "Janak Rawal",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9866212600,
  },
  {
    "S.N.": 21,
    Name: "Karuna Rana",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9819568374,
  },
  {
    "S.N.": 22,
    Name: "Kritika Bajracharya",
    "Membership ID": "BIM KB 419",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9848582867,
  },
  {
    "S.N.": 23,
    Name: "Mahima Shrestha",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9864396216,
  },
  {
    "S.N.": 24,
    Name: "Muna Thokar",
    "Membership ID": "BIM MT 418",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9823489668,
  },
  {
    "S.N.": 25,
    Name: "Pradip Ghalan",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9818200991,
  },
  {
    "S.N.": 26,
    Name: "Prakriti K.C",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9829393284,
  },
  {
    "S.N.": 27,
    Name: "Pranish K.C",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9863270309,
  },
  {
    "S.N.": 28,
    Name: "Prashidha Pratap Rana",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9849441998,
  },
  {
    "S.N.": 29,
    Name: "Pratik Thapa",
    "Membership ID": "BIM PT 440",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9815825484,
  },
  {
    "S.N.": 30,
    Name: "Rajendra Aryal",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9846460958,
  },
  {
    "S.N.": 31,
    Name: "Raman Maharjan",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9803690063,
  },
  {
    "S.N.": 32,
    Name: "Ritish K.C",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9812673310,
  },
  {
    "S.N.": 33,
    Name: "Rizon Ale Magar",
    Faculty: "BIM",
    Semester: "3rd",
    "Phone Number": 9812616025,
  },
  {
    "S.N.": "BCA FOURTH MEMBERSHIP LIST",
  },
  {
    "S.N.": 1,
    Name: "Ashmita Shrestha",
    "Membership ID": "BCA AS 096",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9803373114,
  },
  {
    "S.N.": 2,
    Name: "Bijay Devkota",
    "Membership ID": "BCA BD 097 E",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9866338344,
  },
  {
    "S.N.": 0,
    Name: "Rojina Chhetri",
    "Membership ID": "BCA RC 099 E",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9814887699,
  },
  {
    "S.N.": 4,
    Name: "Tina Adhikari",
    "Membership ID": "BCA TA 100",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9841177993,
  },
  {
    "S.N.": 5,
    Name: "Satish Kumar Mishra",
    "Membership ID": "BCA SKM 130",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9865118789,
  },
  {
    "S.N.": 6,
    Name: "Indira Upadhyay",
    "Membership ID": "BCA IU 035",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9814014780,
  },
  {
    "S.N.": 7,
    Name: "Adarsha Chapagain",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9805170338,
  },
  {
    "S.N.": 8,
    Name: "Alex Maharjan",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9860215171,
  },
  {
    "S.N.": 9,
    Name: "Amit Nagarkoti",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9861546769,
  },
  {
    "S.N.": 10,
    Name: "Anal Bajracharya",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9808229446,
  },
  {
    "S.N.": 11,
    Name: "Aryan Bajracharya",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9861806072,
  },
  {
    "S.N.": 12,
    Name: "Bibek Shrestha",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9813822930,
  },
  {
    "S.N.": 13,
    Name: "Bishesh Rajkarnikar",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9840254868,
  },
  {
    "S.N.": 14,
    Name: "Dristi Shakya",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9840255786,
  },
  {
    "S.N.": 15,
    Name: "Jenish Tandukar",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9860734032,
  },
  {
    "S.N.": 16,
    Name: "Kapil Shrestha",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9803422359,
  },
  {
    "S.N.": 17,
    Name: "Khem Bikram Rana",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9810047004,
  },
  {
    "S.N.": 18,
    Name: "Miken Maharjan 'A'",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9860865493,
  },
  {
    "S.N.": 19,
    Name: "Nikhil Maharjan",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9863201227,
  },
  {
    "S.N.": 20,
    Name: "Nischal Karmacharya",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9840349290,
  },
  {
    "S.N.": 21,
    Name: "Pragya Shakya",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9869524589,
  },
  {
    "S.N.": 22,
    Name: "Rishav Shrestha",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9849831085,
  },
  {
    "S.N.": 23,
    Name: "Rojen Maharjan",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9840032790,
  },
  {
    "S.N.": 24,
    Name: "Ronish Prajapati",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9869374260,
  },
  {
    "S.N.": 25,
    Name: "Salin Maharjan",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9862763452,
  },
  {
    "S.N.": 26,
    Name: "Shreyon Shrestha",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9813091096,
  },
  {
    "S.N.": 27,
    Name: "Sujal Maharjan",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9840521633,
  },
  {
    "S.N.": 28,
    Name: "Suraj Shakya",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9860033997,
  },
  {
    "S.N.": 29,
    Name: "Ujjwal Maharjan 'B'",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9863424564,
  },
  {
    "S.N.": 30,
    Name: "Miken Maharjan 'B'",
    Faculty: "BCS",
    Semester: "4th",
    "Phone Number": 9880290377,
  },
  {
    "S.N.": 31,
    Name: "Ujjwal Maharjan 'A'",
    Faculty: "BCA",
    Semester: "4th",
    "Phone Number": 9808724309,
  },
  {
    "S.N.": "CSIT SECOND SEMESTER MEMBERSHIP LIST",
  },
  {
    "S.N.": 1,
    Name: "Alisha Khatri",
    "Membership ID": "CSIT AK 001",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9842451512,
  },
  {
    "S.N.": 2,
    Name: "Bibusha Shrestha",
    "Membership ID": "CSIT BS 002",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9841446288,
  },
  {
    "S.N.": 3,
    Name: "Kailash Pantha",
    "Membership ID": "CSIT KP 003",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9862568787,
  },
  {
    "S.N.": 4,
    Name: "Nischal Joshi",
    "Membership ID": "CSIT NJ 004",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9847690081,
  },
  {
    "S.N.": 5,
    Name: "Nishant Chaudhary",
    "Membership ID": "CSIT NC 005",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9867085978,
  },
  {
    "S.N.": 6,
    Name: "Reman Khadgi",
    "Membership ID": "CSIT RK 007",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9840087287,
  },
  {
    "S.N.": 7,
    Name: "Sandip Shrestha",
    "Membership ID": "CSIT SS 008",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9813705693,
  },
  {
    "S.N.": 8,
    Name: "Sudil Poudel",
    "Membership ID": "CSIT SP 009",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9849783047,
  },
  {
    "S.N.": 9,
    Name: "Shovit Regmi",
    "Membership ID": "CSIT SR 034",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": "9841386425 \\ 9866599038",
  },
  {
    "S.N.": 10,
    Name: "Akshovya Giri",
    "Membership ID": "CSIT AG 039",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9808161548,
  },
  {
    "S.N.": 11,
    Name: "Cosmic Gautam",
    "Membership ID": "CSIT CG 040",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9884076856,
  },
  {
    "S.N.": 12,
    Name: "Devraj Chapai",
    "Membership ID": "CSIT DC 041",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9848301627,
  },
  {
    "S.N.": 13,
    Name: "Manish Khadka",
    "Membership ID": "CSIT MK 042",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9843162401,
  },
  {
    "S.N.": 14,
    Name: "Raman Achhami",
    "Membership ID": "CSIT RA 043",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9840590787,
  },
  {
    "S.N.": 15,
    Name: "Sandesh Shah",
    "Membership ID": "CSIT SS 415 E",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9860643500,
  },
  {
    "S.N.": 16,
    Name: "Aayush Ayer ",
    "Membership ID": "CSIT AA 362",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9806433384,
  },
  {
    "S.N.": 17,
    Name: "Anurag Bhattari",
    "Membership ID": "CSIT AB 441",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9842863369,
  },
  {
    "S.N.": 18,
    Name: "Bipin Dhami",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": "9817202852 \\ 9745940767",
  },
  {
    "S.N.": 19,
    Name: "Jessica Maharjan",
    "Membership ID": "CSIT JM 367",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9848503095,
  },
  {
    "S.N.": 20,
    Name: "Karishma Thapa",
    "Membership ID": "CSIT KT 358",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9825896493,
  },
  {
    "S.N.": 21,
    Name: "Keship Oli",
    "Membership ID": "CSIT KO 361",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9868810391,
  },
  {
    "S.N.": 22,
    Name: "Kripa Shrestha",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9846799375,
  },
  {
    "S.N.": 23,
    Name: "Kritika Bhatta",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9861823684,
  },
  {
    "S.N.": 24,
    Name: "Nirjal Shahi",
    "Membership ID": "CSIT NS 363",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9869340656,
  },
  {
    "S.N.": 25,
    Name: "Nischal Gautam",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9742873172,
  },
  {
    "S.N.": 26,
    Name: "Pradip Pun",
    "Membership ID": "CSIT PP 364",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9829351429,
  },
  {
    "S.N.": 27,
    Name: "Pratik Adhikari",
    "Membership ID": "CSIT PA 360",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9861443894,
  },
  {
    "S.N.": 28,
    Name: "Pukar Shah",
    "Membership ID": "CSIT PS 448",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9815651020,
  },
  {
    "S.N.": 29,
    Name: "Rakshya Aryal",
    "Membership ID": "CSIT RA 443",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9843954270,
  },
  {
    "S.N.": 30,
    Name: "Rojina Adhikari",
    "Membership ID": "CSIT RA 050",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": "9809269054 \\ 9865273341",
  },
  {
    "S.N.": 31,
    Name: "Samana Maharjan",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9860489599,
  },
  {
    "S.N.": 32,
    Name: "Samikshya Shrestha",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9860982793,
  },
  {
    "S.N.": 33,
    Name: "Sanjana Bajracharya",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9840734631,
  },
  {
    "S.N.": 34,
    Name: "Saugat Panta",
    "Membership ID": "CSIT SP 357",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9813366127,
  },
  {
    "S.N.": 35,
    Name: "Spriha Sharma",
    "Membership ID": "CSIT SS 442",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9880096527,
  },
  {
    "S.N.": 36,
    Name: "Suman Basnet",
    "Membership ID": "CSIT SB 359",
    Faculty: "CSIT",
    Semester: "2nd",
    "Phone Number": 9860826361,
  },
  {
    "S.N.": "CSIT FIFTH SEMESTER MEMBERSHIP LIST ",
  },
  {
    "S.N.": 1,
    Name: "Abhishek Bam",
    "Membership ID": "CSITAB 046",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9862479806,
  },
  {
    "S.N.": 2,
    Name: "Asal Poudel ",
    "Membership ID": "CSIT AP 129",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9863942736,
  },
  {
    "S.N.": 3,
    Name: "Dolma Tamang",
    "Membership ID": "CSIT DT 044",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9864239734,
  },
  {
    "S.N.": 4,
    Name: "Gaurav Dahal",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9804344876,
  },
  {
    "S.N.": 5,
    Name: "Giver Khadka",
    "Membership ID": "CSIT GK 408 E",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": "9811259286/9843382027",
  },
  {
    "S.N.": 6,
    Name: "Hari Prasad Gyawali",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9840755930,
  },
  {
    "S.N.": 7,
    Name: "Jitendra Joshi",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9869085045,
  },
  {
    "S.N.": 8,
    Name: "Krisha Dhakal ",
    "Membership ID": "CSIT KD 032",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9861566979,
  },
  {
    "S.N.": 9,
    Name: "Lal Prasad Shrestha",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9809429301,
  },
  {
    "S.N.": 10,
    Name: "Manav Prasad Nepali",
    "Membership ID": "CSIT MPN 049",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9821683724,
  },
  {
    "S.N.": 11,
    Name: "Manish Shiwakoti",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9866556820,
  },
  {
    "S.N.": 12,
    Name: "Manshi Adhikari",
    "Membership ID": "CSIT MA 047",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9863198475,
  },
  {
    "S.N.": 13,
    Name: "Nirajan Bhattarai",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9847106343,
  },
  {
    "S.N.": 14,
    Name: "Nischal Nandan Karmacharya",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9818353750,
  },
  {
    "S.N.": 15,
    Name: "Nishan Bhattarai",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9860204559,
  },
  {
    "S.N.": 16,
    Name: "Parmeshwor Chaudhary",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9808024942,
  },
  {
    "S.N.": 17,
    Name: "Pragya Maharjan",
    "Membership ID": "CSIT PM 355",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9866410582,
  },
  {
    "S.N.": 18,
    Name: "Rijen Maharjan",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9803468452,
  },
  {
    "S.N.": 19,
    Name: "Rubi Poudel",
    "Membership ID": "CSIT RP 409 E",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9818721206,
  },
  {
    "S.N.": 20,
    Name: "Sadhana Khadka",
    "Membership ID": "CSIT SK 365",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9866296995,
  },
  {
    "S.N.": 21,
    Name: "Sagar Sharma",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9845201639,
  },
  {
    "S.N.": 22,
    Name: "Sahil Pan",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9865460333,
  },
  {
    "S.N.": 23,
    Name: "Samikshya Kunwar",
    "Membership ID": "CSIT SK 038",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9866822081,
  },
  {
    "S.N.": 24,
    Name: "Samyog Dangol",
    "Membership ID": "CSIT SD 048",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9818628291,
  },
  {
    "S.N.": 25,
    Name: "Sanjay Dhamala",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9817917479,
  },
  {
    "S.N.": 26,
    Name: "Shrijan Maharjan",
    "Membership ID": "CSIT SM 045",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9810668866,
  },
  {
    "S.N.": 27,
    Name: "Sijan Karki",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9824754163,
  },
  {
    "S.N.": 28,
    Name: "Sikshya Paudel",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9847786170,
  },
  {
    "S.N.": 29,
    Name: "Subham Khatri",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9814194445,
  },
  {
    "S.N.": 30,
    Name: "Sudip Kumar Yadav",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9803344757,
  },
  {
    "S.N.": 31,
    Name: "Suprem Bhatta",
    "Membership ID": "CSIT SB 369",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9861867533,
  },
  {
    "S.N.": 32,
    Name: "Suraj Kumal",
    "Membership ID": "CSIT SK 368",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9860848360,
  },
  {
    "S.N.": 33,
    Name: "Suravi Shrestha",
    "Membership ID": "CSIT SS 033",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9869579259,
  },
  {
    "S.N.": 34,
    Name: "Tamanna K.C",
    "Membership ID": "CSIT TKC 366",
    Faculty: "CSIT",
    Semester: "5th",
    "Phone Number": 9862575894,
  },
  {
    "S.N.": "CSIT THIRD SEMESTER MEMBERSHIP LIST",
  },
  {
    "S.N.": 1,
    Name: "Abik Maharjan",
    "Membership ID": "CSIT AM 010",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": 9849727160,
  },
  {
    "S.N.": 2,
    Name: "Ashesh Bir Bajracharya",
    "Membership ID": "CSIT ABB 012",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": 9810137701,
  },
  {
    "S.N.": 3,
    Name: "Aisma Thapa",
    "Membership ID": "CSIT AT 011",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": 9847010493,
  },
  {
    "S.N.": 4,
    Name: "Bipasha Hamal",
    "Membership ID": "CSIT BH 013",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": 9841445743,
  },
  {
    "S.N.": 5,
    Name: "Brijesh Dahal",
    "Membership ID": "CSIT BD 014",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": 9861626892,
  },
  {
    "S.N.": 6,
    Name: "Denisha Rai",
    "Membership ID": "CSIT DR 015",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": 9811036164,
  },
  {
    "S.N.": 7,
    Name: "Dipesh Shrestha",
    "Membership ID": "CSIT DS 016",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": 9808437052,
  },
  {
    "S.N.": 8,
    Name: "Loozala Bajracharya",
    "Membership ID": "CSIT LB 017",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": 9860415049,
  },
  {
    "S.N.": 9,
    Name: "Palden Gurung",
    "Membership ID": "CSIT PG 019",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": 9803797273,
  },
  {
    "S.N.": 10,
    Name: "Parash Subedi",
    "Membership ID": "CSIT PS 020",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": 9847303804,
  },
  {
    "S.N.": 11,
    Name: "Rajip Maharjan",
    "Membership ID": "CSIT RM 021",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": 9813794067,
  },
  {
    "S.N.": 12,
    Name: "Rohan Karmacharya",
    "Membership ID": "CSIT RK 022",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": 9841374295,
  },
  {
    "S.N.": 13,
    Name: "Sandesh Dhakal",
    "Membership ID": "CSIT SD 023",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": 9863990339,
  },
  {
    "S.N.": 14,
    Name: "Saugat Maharjan",
    "Membership ID": "CSIT SM 024",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": 9813836061,
  },
  {
    "S.N.": 15,
    Name: "Sishir Chandra Gautam",
    "Membership ID": "CSIT CSG 025",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": 9849539444,
  },
  {
    "S.N.": 16,
    Name: "Shrija Bajracharya",
    "Membership ID": "CSIT SB 026",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": 9803956655,
  },
  {
    "S.N.": 17,
    Name: "Smaran Rawal",
    "Membership ID": "CSIT SR 027",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": 9845301787,
  },
  {
    "S.N.": 18,
    Name: "Sohan Mijar",
    "Membership ID": "CSIT SM 028",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": 9749865362,
  },
  {
    "S.N.": 19,
    Name: "Sulav Bikram Shrestha",
    "Membership ID": "CSIT SBS 029",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": "9860264315 \\ 9842849555",
  },
  {
    "S.N.": 20,
    Name: "Ujjwal Raj Shrestha",
    "Membership ID": "CSIT URS 030",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": 9861609888,
  },
  {
    "S.N.": 21,
    Name: "Uttam K.C",
    "Membership ID": "CSIT UK 031",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": 9862265258,
  },
  {
    "S.N.": 22,
    Name: "Kailash Badu",
    "Membership ID": "CSIT KB 036",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": 9805766454,
  },
  {
    "S.N.": 23,
    Name: "Nilesh Karn",
    "Membership ID": "CSIT NK 018",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": 9821828360,
  },
  {
    "S.N.": 24,
    Name: "Urjala Pariyar",
    "Membership ID": "CSIT UP 411 E",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": 9848856927,
  },
  {
    "S.N.": 25,
    Name: "Dipak Shanki",
    Faculty: "CSIT",
    Semester: "3rd",
    "Phone Number": 9841657581,
  },
  {
    "S.N.": "CSIT SIXTH SEMESTER MEMBERSHIP LIST",
  },
  {
    "S.N.": 1,
    Name: "Aadarsha Bhattarai",
    "Membership ID": "CSIT AB 102",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9840150573,
  },
  {
    "S.N.": 2,
    Name: "Bibek Angdembe",
    "Membership ID": "CSIT BA 104",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9803443845,
  },
  {
    "S.N.": 3,
    Name: "Bikram Bhattarai",
    "Membership ID": "CSIT BB 111",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9824339439,
  },
  {
    "S.N.": 4,
    Name: "Bineet Joshi ",
    "Membership ID": "CSIT BJ 122",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9865894422,
  },
  {
    "S.N.": 5,
    Name: "Binit Thakurathi",
    "Membership ID": "CSIT BT 114",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9880249831,
  },
  {
    "S.N.": 6,
    Name: "Biplav Tharu",
    "Membership ID": "CSIT BT 119",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9816589394,
  },
  {
    "S.N.": 7,
    Name: "Bishal Chaudhary",
    "Membership ID": "CSIT BC 420",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9811988921,
  },
  {
    "S.N.": 8,
    Name: "Chandra Prakash Shah",
    "Membership ID": "CSIT CPS 113",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9869112578,
  },
  {
    "S.N.": 9,
    Name: "Dil Gurung",
    "Membership ID": "CSIT DG 116",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9869020443,
  },
  {
    "S.N.": 10,
    Name: "Garima K.C ",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9840525960,
  },
  {
    "S.N.": 11,
    Name: "Kajool Maharjan",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9849633020,
  },
  {
    "S.N.": 12,
    Name: "Labin Simkhada ",
    "Membership ID": "CSIT LS 117",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9805845996,
  },
  {
    "S.N.": 13,
    Name: "Nabin Bohara",
    "Membership ID": "CSIT NB 124",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9845241117,
  },
  {
    "S.N.": 14,
    Name: "Prateek Bikram Jairu",
    "Membership ID": "CSIT PBJ 127",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9809489700,
  },
  {
    "S.N.": 15,
    Name: "Raj Tuladhar",
    "Membership ID": "CSIT RT 108",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9818609105,
  },
  {
    "S.N.": 16,
    Name: "Rakesh Bhandari",
    "Membership ID": "CSIT RB 128",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9823010796,
  },
  {
    "S.N.": 17,
    Name: "Riju Bohaju",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9861194024,
  },
  {
    "S.N.": 18,
    Name: "Rikesh Shrestha",
    "Membership ID": "CSIT RS 107",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9818648390,
  },
  {
    "S.N.": "Fra ",
    Name: "Ritik Bhandari",
    "Membership ID": "CSIT HBR 123",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9867248850,
  },
  {
    "S.N.": 20,
    Name: "Riwaj Neupane",
    "Membership ID": "CSIT RN 421 E",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9862419169,
  },
  {
    "S.N.": 21,
    Name: "Sajan Mahat",
    "Membership ID": "CSIT SM 417",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9813245166,
  },
  {
    "S.N.": 22,
    Name: "Saksham Kadayat",
    "Membership ID": "CSIT SK 106",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9865630599,
  },
  {
    "S.N.": 23,
    Name: "Samrat Thapa",
    "Membership ID": "CSIT ST 126",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9849455689,
  },
  {
    "S.N.": 24,
    Name: "Sanjaya Khanal",
    "Membership ID": "CSIT SK 103",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9843424386,
  },
  {
    "S.N.": 25,
    Name: "Sarbendra Sigdel",
    "Membership ID": "CSIT SS 146 E",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9860672399,
  },
  {
    "S.N.": 26,
    Name: "Sarthak Shakya",
    "Membership ID": "CSIT SS 407",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9818817448,
  },
  {
    "S.N.": 27,
    Name: "Shishir Shrestha",
    "Membership ID": "CSIT SS 110",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9844539482,
  },
  {
    "S.N.": 28,
    Name: "Shraddha Acharya",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9810339555,
  },
  {
    "S.N.": 29,
    Name: "Sudeep Kumar Mishra",
    "Membership ID": "CSIT SKM 101 E",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9810697766,
  },
  {
    "S.N.": 30,
    Name: "Suraj Gaire",
    "Membership ID": "CSIT SG 112 E",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9869172277,
  },
  {
    "S.N.": 31,
    Name: "Yam Gurung ",
    "Membership ID": "CSIT YG 105",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9808260378,
  },
  {
    "S.N.": 32,
    Name: "Yogesh Sharma",
    "Membership ID": "CSIT YS 109",
    Faculty: "CSIT",
    Semester: "6th",
    "Phone Number": 9824632728,
  },
  {
    "S.N.": "BCA THIRD SEMESTER MEMEBERSHIP LIST",
  },
  {
    "S.N.": 1,
    Name: "Aayush Shrestha",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9808217779,
  },
  {
    "S.N.": 2,
    Name: "Aman Shakya",
    "Membership ID": "BCA AS 422",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9845384872,
  },
  {
    "S.N.": 3,
    Name: "Arbin Bhasima",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9861995164,
  },
  {
    "S.N.": 4,
    Name: "Ashim Gorkhali",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9813536705,
  },
  {
    "S.N.": 5,
    Name: "Biplov Dangol",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9866474870,
  },
  {
    "S.N.": 6,
    Name: "Bishant Kayastha",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 8941368531,
  },
  {
    "S.N.": 7,
    Name: "Chudamani Ojha",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9868725418,
  },
  {
    "S.N.": 8,
    Name: "Isha Shrestha",
    "Membership ID": "BCA IS 446",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9824278287,
  },
  {
    "S.N.": 9,
    Name: "Karan Yadav",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9812137722,
  },
  {
    "S.N.": 10,
    Name: "Laxmi Bhattarai",
    "Membership ID": "BCA LB 410",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9825666755,
  },
  {
    "S.N.": 11,
    Name: "Naman Shipakar",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9869651000,
  },
  {
    "S.N.": 12,
    Name: "Prajit Shrestha",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9813904336,
  },
  {
    "S.N.": 13,
    Name: "Pranish Bajracharya",
    "Membership ID": "BCA PB 412",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9818864259,
  },
  {
    "S.N.": 14,
    Name: "Pushan Maharjan",
    "Membership ID": "BCA PM 432",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9823248793,
  },
  {
    "S.N.": 15,
    Name: "Rahul Chaudhary",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9824600380,
  },
  {
    "S.N.": 16,
    Name: "Rasol Maharjan",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9745616109,
  },
  {
    "S.N.": 17,
    Name: "Rohan Shakya",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9803023580,
  },
  {
    "S.N.": 18,
    Name: "Roman Chitrakar",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9861968626,
  },
  {
    "S.N.": 19,
    Name: "Ronil Shakya",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9818974948,
  },
  {
    "S.N.": 20,
    Name: "Ronish Maharjan",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9840324868,
  },
  {
    "S.N.": 21,
    Name: "Sadhan Shakya",
    "Membership ID": "BCA SS 413",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9749420454,
  },
  {
    "S.N.": 22,
    Name: "Sakura Singh G.C. ",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9823305724,
  },
  {
    "S.N.": 23,
    Name: "Sanju K.C",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9823305724,
  },
  {
    "S.N.": 24,
    Name: "Sarika Budha Magar",
    "Membership ID": "BCA SBM 423",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9803397015,
  },
  {
    "S.N.": 25,
    Name: "Shraya Bhakta Amatya",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9819280127,
  },
  {
    "S.N.": 26,
    Name: "Shree Maharjan",
    "Membership ID": "BCA SM 433",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9861345788,
  },
  {
    "S.N.": 27,
    Name: "Shrey K.C.",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9862907339,
  },
  {
    "S.N.": 28,
    Name: "Siraj Jung Karki",
    "Membership ID": "BCA SJK 414",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9841255678,
  },
  {
    "S.N.": 29,
    Name: "Sujal Ghimire",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9843974494,
  },
  {
    "S.N.": 30,
    Name: "Sujal Shakya (A)",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9843974494,
  },
  {
    "S.N.": 31,
    Name: "Sujal Shakya (B)",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9813059604,
  },
  {
    "S.N.": 32,
    Name: "Sulochana Gyawali",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9819554447,
  },
  {
    "S.N.": 33,
    Name: "Suroj Maharjan",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9886537307,
  },
  {
    "S.N.": 34,
    Name: "Utsab Adhikari",
    "Membership ID": "BCA UA 447",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9821538854,
  },
  {
    "S.N.": 35,
    Name: "Veerin Bajracharya",
    "Membership ID": "BCA VB 424",
    Faculty: "BCA",
    Semester: "3rd",
    "Phone Number": 9860316674,
  },

  {
    "S.N.": "BIM SIXTH SEMESTER MEMEBERSHIP LIST",
  },
  {
    "S.N.": 1,
    Name: "Bibek Lama",
    "Membership ID": "BIM BL 416 E",
    Faculty: "BIM",
    Semester: "6th",
    "Phone Number": 9803507666,
  },

  {
    "S.N.": "BBM THIRD SEMESTER MEMBERSHIP LIST",
  },
  {
    "S.N.": 1,
    Name: "Nishma Bastakoti",
    "Membership ID": "BBM NB 401 E",
    Faculty: "BBM",
    Semester: "3rd",
    "Phone Number": 9861396019,
  },
  {
    "S.N.": 2,
    Name: "Anjali Pokharel",
    "Membership ID": "BBM AP 444",
    Faculty: "BBM",
    Semester: "3rd",
    "Phone Number": 9749355528,
  },

  {
    "S.N.": "BBM FIFTH SEMESTER MEMBERSHIP LIST",
  },
  {
    "S.N.": 1,
    Name: "Dolma Thokar",
    "Membership ID": "BBM DT 425",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": 9745957159,
  },
  {
    "S.N.": 2,
    Name: "Sushina Maharjan",
    "Membership ID": "BBM SM 430",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": 9867815926,
  },
  {
    "S.N.": 3,
    Name: "Saroj Shrestha",
    "Membership ID": "BBM SS 429",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": 9864489015,
  },
  {
    "S.N.": 4,
    Name: "Sarah Sunuwar",
    "Membership ID": "BBM SS 428",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": 9843882346,
  },
  {
    "S.N.": 5,
    Name: "Sabbu Silwal",
    "Membership ID": "BBM SS 427",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": 9861043224,
  },
  {
    "S.N.": 6,
    Name: "Nikita Dotel",
    "Membership ID": "BBM ND 426",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": 9844275946,
  },
  {
    "S.N.": 7,
    Name: "Aashish Thapa Magar",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": 9861382629,
  },
  {
    "S.N.": 8,
    Name: "Abishekh Roka",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": 9864104746,
  },
  {
    "S.N.": 9,
    Name: "Ajay Sapkota",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": 9803285920,
  },
  {
    "S.N.": 10,
    Name: "Akash Bhatt",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": 9810775920,
  },
  {
    "S.N.": 11,
    Name: "Anisha Thapa",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": 9741757928,
  },
  {
    "S.N.": 12,
    Name: "Bibisha G.C",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": 9864021354,
  },
  {
    "S.N.": 13,
    Name: "Biraj Bist",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": "9810932426 \\ 9866599224",
  },
  {
    "S.N.": 14,
    Name: "Ganesh Bist",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": "9865735322 \\ 9809462347",
  },
  {
    "S.N.": 15,
    Name: "Laxmi Ale Magar",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": 9814745941,
  },
  {
    "S.N.": 16,
    Name: "Nitesh Joshi",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": 9806468040,
  },
  {
    "S.N.": 17,
    Name: "Prashin Poudel",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": 9841481244,
  },
  {
    "S.N.": 18,
    Name: "Pratikshya Kunwar",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": 9808079667,
  },
  {
    "S.N.": 19,
    Name: "Rabina Kumari Chaudhary",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": 9809364287,
  },
  {
    "S.N.": 20,
    Name: "Refika Maharjan",
    "Membership ID": "BBM RM 352",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": 9863349077,
  },
  {
    "S.N.": 21,
    Name: "Sapana Rawat",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": 9813322835,
  },
  {
    "S.N.": 22,
    Name: "Simon Maharjan",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": 9863328239,
  },
  {
    "S.N.": 23,
    Name: "Soni Chaudhary",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": 9869229720,
  },
  {
    "S.N.": 24,
    Name: "Sujan Karki",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": 9847646691,
  },
  {
    "S.N.": 25,
    Name: "Sulochana Maharjan",
    "Membership ID": "BBM SM 353",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": 9808413775,
  },
  {
    "S.N.": 26,
    Name: "Tara Bahadur Khatri",
    Faculty: "BBM",
    Semester: "5th",
    "Phone Number": 9860718927,
  },

  {
    "S.N.": "BIM SECOND SEMESTER MEMBERSHIP LIST",
  },
  {
    "S.N.": 1,
    Name: "Afsana Husain",
    "Membership ID": "BIM AH 435",
    Faculty: "BIM",
    Semester: "2nd",
    "Phone Number": 9812178868,
  },
  {
    "S.N.": 2,
    Name: "Aman Adhikari",
    "Membership ID": "BIM AA 436",
    Faculty: "BIM",
    Semester: "2nd",
    "Phone Number": 9840265103,
  },
  {
    "S.N.": 3,
    Name: "Mandip Shrestha",
    "Membership ID": "BIM MS 437",
    Faculty: "BIM",
    Semester: "2nd",
    "Phone Number": 9862711096,
  },
  {
    "S.N.": 4,
    Name: "Sandesh Shrestha",
    "Membership ID": "BIM SS 438",
    Faculty: "BIM",
    Semester: "2nd",
    "Phone Number": 9808128209,
  },
  {
    "S.N.": 5,
    Name: "Sujal Thapa ",
    "Membership ID": "BIM ST 439",
    Faculty: "BIM",
    Semester: "2nd",
    "Phone Number": 9845997900,
  },

  {
    "S.N.": "BCA SECOND SEMESTER MEMBERSHIP LIST",
  },
  {
    "S.N.": 1,
    Name: "Ramratan Prasad Kushwaha",
    "Membership ID": "BCA RPK 445",
    Faculty: "BCA",
    Semester: "2nd",
    "Phone Number": 9866122839,
  },
  {
    "S.N.": 2,
    Name: "Aradhana Rijal",
    "Membership ID": "BCA AR 449",
    Faculty: "BCA",
    Semester: "2nd",
    "Phone Number": 9809799605,
  },
  {
    "S.N.": 3,
    Name: "Sujita Shrestha",
    "Membership ID": "BCA SS 450",
    Faculty: "BCA",
    Semester: "2nd",
    "Phone Number": 9745559284,
  },
  {
    "S.N.": 4,
    Name: "Swayam Shrestha",
    "Membership ID": "BCA SS 351",
    Faculty: "BCA",
    Semester: "2nd",
    "Phone Number": 9866473259,
  },
];
